### ISSUE TITLE
1.4rc3 error on base attack

### ISSUE THREAD

**Issue by MaHuJa** [shdwp/dcs_liberation#23]
```
INFO:root:DCS Libration None
INFO:root:Using C:\Users\MaHuJa\Saved Games\DCS.openbeta as userdata folder
INFO:root:<theater.base.Base object at 0x000000000422C128> for <class 'dcs.task.CAP'> (0): {<class 'dcs.planes.C_101CC'>: 1}
INFO:root:<theater.base.Base object at 0x000000000422C128> for <class 'dcs.task.CAS'> (0): {<class 'dcs.planes.Su_25T'>: 1}
INFO:root:<theater.base.Base object at 0x000000000422C128>: no units for <class 'dcs.vehicles.AirDefence'>
INFO:root:Generating Base attack (regular)
ERROR:root:<class 'TypeError'>
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "E:\dcs_liberation\ui\eventmenu.py", line 186, in start
    self.game.initiate_event(self.event)
  File "E:\dcs_liberation\game\game.py", line 212, in initiate_event
    event.generate()
  File "E:\dcs_liberation\game\event\event.py", line 79, in generate
    self.operation.generate()
  File "E:\dcs_liberation\game\operation\baseattack.py", line 50, in generate
    self.armorgen.generate(self.attack, self.defense)
  File "E:\dcs_liberation\gen\armor.py", line 85, in generate
    at=self.conflict.ground_attackers_location)
  File "E:\dcs_liberation\gen\armor.py", line 38, in _generate_group
    for c in range(count):
TypeError: 'tuple' object cannot be interpreted as an integer
```

Pulled by git, at the 1.4_rc3 revision.

**Comment by shdwp** [comment]
Found the issue, will be fixed in next build.

**Comment by MaHuJa** [comment]
I've updated to a later version (current dev, 8431c7) where we have more problems in the same vein.
Generating Destroy insurgents (regular) 
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
INFO:root:Pass turn
INFO:root:Generating Destroy insurgents (regular)
INFO:root:airgen: <class 'dcs.planes.FA_18C_hornet'> for 2 at <class 'dcs.terrain.caucasus.Soganlug'>
ERROR:root:<class 'TypeError'>
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "E:\dcs_liberation\ui\eventmenu.py", line 186, in start
    self.game.initiate_event(self.event)
  File "E:\dcs_liberation\game\game.py", line 212, in initiate_event
    event.generate()
  File "E:\dcs_liberation\game\event\event.py", line 79, in generate
    self.operation.generate()
  File "E:\dcs_liberation\game\operation\insurgentattack.py", line 31, in generate
    self.airgen.generate_defenders_cas(*assigned_units_split(self.strikegroup), at=self.defenders_starting_position)
  File "E:\dcs_liberation\gen\aircraft.py", line 309, in generate_defenders_cas
    insertion_point = self.conflict.find_insertion_point(location)
  File "E:\dcs_liberation\gen\conflictgen.py", line 133, in find_insertion_point
    dx = self.position.x - self.tail.x
  File "E:\dcs_liberation\gen\conflictgen.py", line 118, in tail
    return self.position.point_from_heading(self.heading, self.distance)
  File "E:\dcs_liberation\dcs\mapping.py", line 62, in point_from_heading
    x, y = point_from_heading(self.x, self.y, heading, distance)
  File "E:\dcs_liberation\dcs\mapping.py", line 16, in point_from_heading
    while heading < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

It appears these need to be tested systematically - the price paid for using a run time type resolved language.j

**Comment by shdwp** [comment]
I've had some kind of integration testing in mind to test the events from start to finish, but it looks like a boring enough task so it gets rescheduled again and again.

**Comment by MaHuJa** [comment]
What you really need is a script that'll create all the mission types with all the plane types, overwriting the produced mission in each go. Think running tools\test.py and getting all those error reports in one go.

I'm presuming each function is disentangled enough to call without the whole gui being loaded etc. I haven't looked much at the internals. Yet.

**Comment by shdwp** [comment]
Yeah, thats exactly what I meant by "integration testing".
