### ISSUE TITLE
Static Object "dead" event without Name

### ISSUE THREAD

**Issue by calvinmorrow** [shdwp/dcs_liberation#49]
Ran into an interesting error while playtesting today:

At mission start the following events occur:
```events = 
{
	[1] = 
	{
		type	=	"dead",
		t	=	28800,
		initiatorMissionID	=	"69",
		initiator	=	"SKLAD_CRUSH",
	}, -- end of [1]
	[2] = 
	{
		type	=	"dead",
		t	=	28800,
		initiatorMissionID	=	"70",
		initiator	=	"ANGAR_A_CRUSH",
	}, -- end of [2]
	[3] = 
	{
		type	=	"dead",
		t	=	28800,
		initiatorMissionID	=	"71",
		initiator	=	"ANGAR_A_CRUSH",
	}, -- end of [3]
	[4] = 
	{
		type	=	"mission start",
		t	=	28800,
	}, -- end of [4]
```

which as far as I can tell is causing the following traceback during a multiplayer debriefing:

```Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\calvinmorrow\Desktop\dcs_liberation_1.4.5\userdata\debriefing.py", line 192, in _poll_new_debriefing_log
    callback(debriefing)
  File "C:\Users\calvinmorrow\Desktop\dcs_liberation_1.4.5\ui\eventresultsmenu.py", line 113, in process_debriefing
    enemy_name=self.game.enemy)
  File "C:\Users\calvinmorrow\Desktop\dcs_liberation_1.4.5\userdata\debriefing.py", line 161, in calculate_units
    assert str(group.name)
AssertionError
```

Offending code snippet: (Lines 156-161)
```
        for group in static_groups:
            identifier = group.units[0].id
            if identifier in self._dead_units:
                logging.info("debriefing: found dead static {} ({})".format(str(group.name), identifier))

                assert str(group.name)
```

[debrief.log](https://github.com/shdwp/dcs_liberation/files/2546305/debrief.log)

**Comment by shdwp** [comment]
Fixed and scheduled for next release.

**Comment by shdwp** [comment]
And, yeah, thanks @calvinmorrow for the fix.
