### ISSUE TITLE
missing target.png

### ISSUE THREAD

**Issue by JohanAberg** [shdwp/dcs_liberation#53]
Hi team,

I'm new to this code base and I was just trying the development version and there seems to be missing files.
Please see Traceback below.

Can you see anything obvious I am doing wrong?
I'm at commit: `f7e2c892`

`
ERROR:root:<class 'pygame.error'>
Traceback (most recent call last):
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\Johan\PycharmProjects\dcs_liberation\ui\newgamemenu.py", line 133, in proceed
    float(self.multiplier.get()))
  File "C:\Users\Johan\PycharmProjects\dcs_liberation\ui\window.py", line 115, in start_new_game
    self.proceed_to_main_menu(game)
  File "C:\Users\Johan\PycharmProjects\dcs_liberation\ui\window.py", line 120, in proceed_to_main_menu
    m = MainMenu(self, None, game)
  File "C:\Users\Johan\PycharmProjects\dcs_liberation\ui\mainmenu.py", line 19, in __init__
    self.upd = OverviewCanvas(self.window.left_pane, self, game)
  File "C:\Users\Johan\PycharmProjects\dcs_liberation\ui\overviewcanvas.py", line 94, in __init__
    self.init_sdl_layer()
  File "C:\Users\Johan\PycharmProjects\dcs_liberation\ui\overviewcanvas.py", line 136, in init_sdl_layer
    self.ground_assets_icons["target"] = pygame.image.load(os.path.join("resources", "ui", "ground_assets", "target.png"))
pygame.error: Couldn't open resources\ui\ground_assets\target.png
`
This is a great project, nice one!
Cheers

**Comment by Khopa** [comment]
Yes, there are a few files missing on the develop branch currently. 

I made a pull request with the files.  (https://github.com/shdwp/dcs_liberation/pull/54)
You can also get them on my fork https://github.com/khopa/dcs_liberation on branch *develop_khopa*

I think @shdwp had things in progress, cause currently it doesn't work well for me.

**Comment by Khopa** [comment]
And you can checkout commit 97be483624815a09a6ba2ac17836f5cf221dcda2 on develop branch, for a version that i believe is working and has the correct files.

**Comment by JohanAberg** [comment]
ok thanks, I'll try your fork, cheers!
