### ISSUE TITLE
Is the qt_ui branch testable?

### ISSUE THREAD

**Issue by DeusEx010101** [shdwp/dcs_liberation#76]
I am interested in contributing but have been having issues getting this branch to run locally.

Traceback (most recent call last):
  File "G:/DW-FILE-LIBRARY/_000_Work/DCS-mods/dcs_liberation/qt_ui/main.py", line 58, in <module>
    window = QLiberationWindow()
  File "G:\DW-FILE-LIBRARY\_000_Work\DCS-mods\dcs_liberation\qt_ui\windows\QLiberationWindow.py", line 29, in __init__
    self.initUi()
  File "G:\DW-FILE-LIBRARY\_000_Work\DCS-mods\dcs_liberation\qt_ui\windows\QLiberationWindow.py", line 39, in initUi
    self.liberation_map = QLiberationMap(self.game)
  File "G:\DW-FILE-LIBRARY\_000_Work\DCS-mods\dcs_liberation\qt_ui\widgets\map\QLiberationMap.py", line 43, in __init__
    self.setGame(game)
  File "G:\DW-FILE-LIBRARY\_000_Work\DCS-mods\dcs_liberation\qt_ui\widgets\map\QLiberationMap.py", line 61, in setGame
    self.reload_scene()
  File "G:\DW-FILE-LIBRARY\_000_Work\DCS-mods\dcs_liberation\qt_ui\widgets\map\QLiberationMap.py", line 122, in reload_scene
    if cp.id in self.game.planners.keys():
AttributeError: 'Game' object has no attribute 'planners'

Process finished with exit code 1

**Comment by Khopa** [comment]
Hello, 

Yes you can run it. 

You are having this problem, because the qt_ui branch is not compatible with the stable branch save game format.

So you have to delete the liberation_save from your the DCS save folders (C:/Users/<name>/Documents/Saved Games/DCS/liberation_save) and you will be able to run

**Comment by DeusEx010101** [comment]
Works! Thank you.
Wow. This is an amazing improvement. You have done a ton of work.

**Comment by Khopa** [comment]
Thanks :smile: 

You can join the discord if you want to discuss the new features and provide feedback : https://discord.gg/bKrtrkJ
