### ISSUE TITLE
Debrief error after second mission

### ISSUE THREAD

**Issue by FleMo93** [shdwp/dcs_liberation#87]
When finish the second mission there is always an error on the console when copying the debrief.log in the directory.  This is happing when playing singleplayer or multiplayer. Tried it two times. Started a new campaing and delete the save before.

Using Liberation 1.5.2.2  
DCS Open Beta 2.5.5.41371
```
Hello from the pygame community. https://www.pygame.org/contribute.html
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
Started SDL app
Base didn't find event type <class 'dcs.vehicles.AirDefence.SAM_SA_9_Strela_1_9P31'>
Base didn't find event type <class 'dcs.vehicles.Unarmed.Transport_Ural_375'>
Base didn't find event type <class 'dcs.vehicles.AirDefence.SAM_SA_19_Tunguska_2S6'>
Exception in thread Thread-3:


Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
    self.run()
  File "threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "userdata\debriefing.py", line 208, in _poll_new_debriefing_log
  File "ui\eventresultsmenu.py", line 115, in process_debriefing
  File "game\game.py", line 251, in finish_event
  File "game\event\convoystrike.py", line 49, in commit
  File "game\event\convoystrike.py", line 56, in is_successfull
  File "game\event\convoystrike.py", line 56, in <listcomp>
  File "game\db.py", line 477, in unit_task
AssertionError
```

Tried to do the convoy mission with one A10C.

[debrief.log](https://github.com/shdwp/dcs_liberation/files/4050911/debrief.log)
[liberation_save.txt](https://github.com/shdwp/dcs_liberation/files/4050912/liberation_save.txt)
[liberation_save_tmp.txt](https://github.com/shdwp/dcs_liberation/files/4050918/liberation_save_tmp.txt)

**Comment by wrycu** [comment]
@FleMo93 which mission are you attempting?  What forces do you have involved in it?

**Comment by FleMo93** [comment]
@wrycu See my last sentence. I tried the convoy mission north the start base with only an A10C as client.

I retried it in so Singleplayer and it works well there. I absolutely missed to press the "save Debriefing" button after exited the mission. Absolutely my fault. But am I mission something else in multiplayer?
When I play it with a friend after landing at home base and turning down the planes we go to role selection, press "load mission" button and reload the same mission.

**Comment by wrycu** [comment]
Sorry, missed the last sentence there. Will take a look at this.

**Comment by FleMo93** [comment]
We tried it again today in coop. It is only this special convoy mission in the north. We flew with 2 A10C and destroyed some extra targets.   
```
Hello from the pygame community. https://www.pygame.org/contribute.html
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
Started SDL app
Base didn't find event type <class 'dcs.planes.IL_78M'>
Base didn't find event type <class 'dcs.vehicles.Unarmed.Transport_UAZ_469'>
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
    self.run()
  File "threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "userdata\debriefing.py", line 208, in _poll_new_debriefing_log
  File "ui\eventresultsmenu.py", line 113, in process_debriefing
  File "userdata\debriefing.py", line 177, in calculate_units
AssertionError

Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
    self.run()
  File "threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "userdata\debriefing.py", line 208, in _poll_new_debriefing_log
  File "ui\eventresultsmenu.py", line 113, in process_debriefing
  File "userdata\debriefing.py", line 177, in calculate_units
AssertionError
```
[debrief.log](https://github.com/shdwp/dcs_liberation/files/4083226/debrief.log)
[liberation_save.txt](https://github.com/shdwp/dcs_liberation/files/4083230/liberation_save.txt)
[liberation_save_tmp.txt](https://github.com/shdwp/dcs_liberation/files/4083231/liberation_save_tmp.txt)

**Comment by wrycu** [comment]
I can't reproduce this issue on the latest build using your save and log file. Try again with the next release (1.6 - not out yet) and reopen if you still have an issue.
